Update vimg
timg chg

diff --git a/scripts/vimg b/scripts/vimg
--- a/scripts/vimg
+++ b/scripts/vimg
@@ -13,28 +13,24 @@ function render_at_size {
   max_height="${2}"
   img_path="${3}"
 
-  # animation is turned off as it does werid things with the terminal output
-  chafa --animate=off --center=on --clear --size "${max_width}x${max_height}" "${img_path}"
+  # Using timg for rendering images
+  timg -g "${tomax_width}x${max_height}" "${img_path}"
 }
 
 function draw_preview {
-    if ! command -v chafa &> /dev/null; then
-      echo "chafa could not be found in your path,\nplease install it to display media content"
+    if ! command -v timg &> /dev/null; then
+      echo "timg could not be found in your path,\nplease install it to display media content"
       exit
     fi
 
     if [[ "$1" == "imagepreview" ]]; then
       render_at_size "${5}" "${6}" "${2}" "${7}"
-      # viu -b -w ${5} -h ${6} "${2}"
 
     elif [[ "$1" == "gifpreview" ]]; then
-      # This is static for now, feel free to re-introduce FIFO to make
-      # animations work again, plaing viu gifs (removing the -s flag) causes
-      # the preview window to scroll weirdly
       render_at_size "${5}" "${6}" "${2}" "${7}"
 
     elif [[ "$1" == "videopreview" ]]; then
-      if ! command -v viu &> /dev/null; then
+      if ! command -v ffmpegthumbnailer &> /dev/null; then
         echo "ffmpegthumbnailer could not be found in your path,\nplease install it to display video previews"
         exit
       fi
